//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CenterServicesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CenterServicesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDS_SanadDistributedSystem.Resources.CenterServicesResource", typeof(CenterServicesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الخدمة.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء تفعيل الخدمة.
        /// </summary>
        public static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المركز.
        /// </summary>
        public static string idcenter_FK {
            get {
                return ResourceManager.GetString("idcenter_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمة.
        /// </summary>
        public static string idservice_FK {
            get {
                return ResourceManager.GetString("idservice_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بدء تفعيل الخدمة.
        /// </summary>
        public static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
    }
}
