//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonAndFamilyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonAndFamilyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDS_SanadDistributedSystem.Resources.PersonAndFamilyResources", typeof(PersonAndFamilyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الولادة.
        /// </summary>
        public static string birthplace {
            get {
                return ResourceManager.GetString("birthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الحالي.
        /// </summary>
        public static string currentaddress {
            get {
                return ResourceManager.GetString("currentaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النزوح.
        /// </summary>
        public static string displacementdate {
            get {
                return ResourceManager.GetString("displacementdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليم.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة التعليمية.
        /// </summary>
        public static string educationstate {
            get {
                return ResourceManager.GetString("educationstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم.
        /// </summary>
        public static string evaluation {
            get {
                return ResourceManager.GetString("evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبيعة العائلة.
        /// </summary>
        public static string familynature {
            get {
                return ResourceManager.GetString("familynature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأب.
        /// </summary>
        public static string fathername {
            get {
                return ResourceManager.GetString("fathername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الاستمارة.
        /// </summary>
        public static string formnumber {
            get {
                return ResourceManager.GetString("formnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم دفتر العائلة.
        /// </summary>
        public static string idfamily {
            get {
                return ResourceManager.GetString("idfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم التسلسلي للقائمة.
        /// </summary>
        public static string idmanagelist {
            get {
                return ResourceManager.GetString("idmanagelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم التسلسلي للمستخدم.
        /// </summary>
        public static string iduser {
            get {
                return ResourceManager.GetString("iduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان السابق.
        /// </summary>
        public static string lastaddress {
            get {
                return ResourceManager.GetString("lastaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير.
        /// </summary>
        public static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز المميز للقائمة.
        /// </summary>
        public static string managelist_flag {
            get {
                return ResourceManager.GetString("managelist_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم عنصر القائمة.
        /// </summary>
        public static string managelist_name {
            get {
                return ResourceManager.GetString("managelist_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوضع العائلي.
        /// </summary>
        public static string martial {
            get {
                return ResourceManager.GetString("martial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الأم.
        /// </summary>
        public static string mothername {
            get {
                return ResourceManager.GetString("mothername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الوطني.
        /// </summary>
        public static string nationalnumber {
            get {
                return ResourceManager.GetString("nationalnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم التسلسلي للشخص.
        /// </summary>
        public static string person_id {
            get {
                return ResourceManager.GetString("person_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد أفراد العائلة.
        /// </summary>
        public static string personcount {
            get {
                return ResourceManager.GetString("personcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف 1.
        /// </summary>
        public static string phone1 {
            get {
                return ResourceManager.GetString("phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالك الهاتف 1.
        /// </summary>
        public static string phone1owner {
            get {
                return ResourceManager.GetString("phone1owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف 2.
        /// </summary>
        public static string phone2 {
            get {
                return ResourceManager.GetString("phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالك الهاتف 2.
        /// </summary>
        public static string phone2owner {
            get {
                return ResourceManager.GetString("phone2owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        public static string registrationdate {
            get {
                return ResourceManager.GetString("registrationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العلاقة مع مقدم الطلب.
        /// </summary>
        public static string relationtype {
            get {
                return ResourceManager.GetString("relationtype", resourceCulture);
            }
        }
    }
}
