//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class referalpersonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal referalpersonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDS_SanadDistributedSystem.Resources.referalpersonResource", typeof(referalpersonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير الحالة.
        /// </summary>
        public static string Case_Manager {
            get {
                return ResourceManager.GetString("Case_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المركز.
        /// </summary>
        public static string idcenter_FK {
            get {
                return ResourceManager.GetString("idcenter_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم التسلسلي.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string outreachnote {
            get {
                return ResourceManager.GetString("outreachnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشخص.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقيم المستقبل.
        /// </summary>
        public static string recieverevalution {
            get {
                return ResourceManager.GetString("recieverevalution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإحالة.
        /// </summary>
        public static string referaldate {
            get {
                return ResourceManager.GetString("referaldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستقبل.
        /// </summary>
        public static string referalreicver_FK {
            get {
                return ResourceManager.GetString("referalreicver_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرسل.
        /// </summary>
        public static string referalsender_FK {
            get {
                return ResourceManager.GetString("referalsender_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الإحالة.
        /// </summary>
        public static string referalstate {
            get {
                return ResourceManager.GetString("referalstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقيم أولي.
        /// </summary>
        public static string senderevalution {
            get {
                return ResourceManager.GetString("senderevalution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الخدمة.
        /// </summary>
        public static string Service_Type {
            get {
                return ResourceManager.GetString("Service_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إنهاء الخدمة.
        /// </summary>
        public static string serviceenddate {
            get {
                return ResourceManager.GetString("serviceenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بدء الخدمة.
        /// </summary>
        public static string servicestartdate {
            get {
                return ResourceManager.GetString("servicestartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الخدمة.
        /// </summary>
        public static string servicestate {
            get {
                return ResourceManager.GetString("servicestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإرسال.
        /// </summary>
        public static string submittingdate {
            get {
                return ResourceManager.GetString("submittingdate", resourceCulture);
            }
        }
    }
}
