//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Models
{
    using System;
    using System.Collections.Generic;
    using Resources;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class family
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public family()
        {
            this.familymanages = new HashSet<familymanage>();
            this.people = new HashSet<person>();
            this.referalfamilies = new HashSet<referalfamily>();
        }

        //[Required]
        //[Display(Name = "idfamily", ResourceType = typeof(PersonAndFamilyResources))]
        public int idfamily { get; set; }
        [Display(Name = "familynature", ResourceType = typeof(PersonAndFamilyResources))]
        public string familynature { get; set; }
        [Display(Name = "lname", ResourceType = typeof(PersonAndFamilyResources))]
        public string lastname { get; set; }
        [Display(Name = "personcount", ResourceType = typeof(PersonAndFamilyResources))]
        public Nullable<int> personcount { get; set; }
        [Display(Name = "lastaddress_details", ResourceType = typeof(PersonAndFamilyResources))]
        public string lastaddress_details { get; set; }
        [Display(Name = "currentaddress_details", ResourceType = typeof(PersonAndFamilyResources))]
        public string currentaddress_details { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date, ErrorMessage = "’Ì€… «· «—ÌŒ €Ì— ’ÕÌÕ…")]
        [Display(Name = "displacementdate", ResourceType = typeof(PersonAndFamilyResources))]
        public Nullable<System.DateTime> displacementdate { get; set; }
        [Required]
        [StringLength(10)]
        [RegularExpression(@"^[0-9]+$")]
        [Display(Name = "phone1", ResourceType = typeof(PersonAndFamilyResources))]
        public string phone1 { get; set; }
        [StringLength(10)]
        [RegularExpression(@"^[0-9]+$")]
        [Display(Name = "phone2", ResourceType = typeof(PersonAndFamilyResources))]
        public string phone2 { get; set; }
        [Display(Name = "note", ResourceType = typeof(PersonAndFamilyResources))]
        public string note { get; set; }
        [Display(Name = "iduser", ResourceType = typeof(PersonAndFamilyResources))]
        public string iduser { get; set; }
        [Required]
        [Display(Name = "phone1owner", ResourceType = typeof(PersonAndFamilyResources))]
        public string phone1owner { get; set; }
        [Display(Name = "phone2owner", ResourceType = typeof(PersonAndFamilyResources))]
        public string phone2owner { get; set; }
        [Display(Name = "evaluation", ResourceType = typeof(PersonAndFamilyResources))]
        public Nullable<int> evaluation { get; set; }
        [Display(Name = "formnumber", ResourceType = typeof(PersonAndFamilyResources))]
        public Nullable<int> formnumber { get; set; }
        public string idcenter_FK { get; set; }
        [Display(Name = "serial_number", ResourceType = typeof(PersonAndFamilyResources))]
        public string serial_number { get; set; }
        [Remote("familyBookNumberAlreadyExisted", "families",
            ErrorMessageResourceType = typeof(ErrorResource),
            ErrorMessageResourceName = "family_book_number_existed", AdditionalFields = "idfamily", HttpMethod = "Post")
            ]
        [RegularExpression(@"^[0-9]+$")]
        [Required]
        [Display(Name = "family_book_number", ResourceType = typeof(PersonAndFamilyResources))]
        public string family_book_number { get; set; }
        [Display(Name = "family_head", ResourceType = typeof(PersonAndFamilyResources))]
        public string family_head { get; set; }
        [Display(Name = "sector", ResourceType = typeof(PersonAndFamilyResources))]
        public string sector { get; set; }
        [Display(Name = "is_visited", ResourceType = typeof(PersonAndFamilyResources))]
        public bool is_visited { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date, ErrorMessage = "’Ì€… «· «—ÌŒ €Ì— ’ÕÌÕ…")]
        [Display(Name = "last_visit_date", ResourceType = typeof(PersonAndFamilyResources))]
        public Nullable<System.DateTime> last_visit_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual center center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<familymanage> familymanages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<person> people { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referalfamily> referalfamilies { get; set; }
    }
}
