//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Models
{
    using Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class managelist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public managelist()
        {
            this.families = new HashSet<family>();
            this.personmanages = new HashSet<personmanage>();
        }

        [Display(Name = "idmanagelist", ResourceType = typeof(PersonAndFamilyResources))]
        public int idmanagelist { get; set; }
        [Display(Name = "managelist_name", ResourceType = typeof(PersonAndFamilyResources))]
        public string name { get; set; }

        [StringLength(3)]
        [Required]
        [Remote("flagAlreadyExisted", "managelists",
            ErrorMessageResourceType = typeof(ErrorResource),
            ErrorMessageResourceName = "id_existed")
            ]
        [Display(Name = "managelist_flag", ResourceType = typeof(PersonAndFamilyResources))]
        public string flag { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<family> families { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personmanage> personmanages { get; set; }
    }
}
