//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personmanage
    {
        public string idperson_FK { get; set; }
        public int idmanagelist_FK { get; set; }
        public string eval { get; set; }
    
        public virtual managelist managelist { get; set; }
        public virtual person person { get; set; }
    }
}
