//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sds_dbEntities : DbContext
    {
        public sds_dbEntities()
            : base("name=sds_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<@case> cases { get; set; }
        public virtual DbSet<center> centers { get; set; }
        public virtual DbSet<managelist> managelists { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<referalfamily> referalfamilies { get; set; }
        public virtual DbSet<referalperson> referalpersons { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<temporal> temporals { get; set; }
        public virtual DbSet<family> families { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<personmanage> personmanages { get; set; }
    }
}
