//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Models
{
    using System;
    using System.Collections.Generic;
    using Resources;
    using System;


    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class temporal
    {
        [Display(Name = "person_id", ResourceType = typeof(PersonAndFamilyResources))]
        public string idperson { get; set; }
        [Display(Name = "fname", ResourceType = typeof(PersonAndFamilyResources))]
        public string fname { get; set; }
        [Display(Name = "lname", ResourceType = typeof(PersonAndFamilyResources))]
        public string lname { get; set; }
        [Display(Name = "fathername", ResourceType = typeof(PersonAndFamilyResources))]
        public string fathername { get; set; }
        [Display(Name = "mothername", ResourceType = typeof(PersonAndFamilyResources))]
        public string mothername { get; set; }
        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "birthday", ResourceType = typeof(PersonAndFamilyResources))]
        public Nullable<System.DateTime> birthday { get; set; }
        [Display(Name = "birthplace", ResourceType = typeof(PersonAndFamilyResources))]
        public string birthplace { get; set; }
        [Display(Name = "gender", ResourceType = typeof(PersonAndFamilyResources))]
        public string gender { get; set; }
        [Display(Name = "nationality", ResourceType = typeof(PersonAndFamilyResources))]
        public string nationality { get; set; }
        [Display(Name = "martial", ResourceType = typeof(PersonAndFamilyResources))]
        public string martial { get; set; }
        [Display(Name = "relationtype", ResourceType = typeof(PersonAndFamilyResources))]
        public string relationtype { get; set; }
        public string onoffflag { get; set; }
        [Display(Name = "education", ResourceType = typeof(PersonAndFamilyResources))]
        public string education { get; set; }
        [Display(Name = "educationstate", ResourceType = typeof(PersonAndFamilyResources))]
        public string educationstate { get; set; }
        [Display(Name = "phone1", ResourceType = typeof(PersonAndFamilyResources))]
        public string phone1 { get; set; }
        [Display(Name = "phone2", ResourceType = typeof(PersonAndFamilyResources))]
        public string phone2 { get; set; }
        [Display(Name = "currentaddress", ResourceType = typeof(PersonAndFamilyResources))]
        public string currentaddress { get; set; }
        [Display(Name = "registrationdate", ResourceType = typeof(PersonAndFamilyResources))]
        public Nullable<System.DateTimeOffset> tempregistrationdate { get; set; }
        public string idcenter_FK { get; set; }
        [Display(Name = "formnumber", ResourceType = typeof(PersonAndFamilyResources))]
        public Nullable<int> formnumber { get; set; }
        [Display(Name = "note", ResourceType = typeof(PersonAndFamilyResources))]
        public string note { get; set; }
        public string iduser_FK { get; set; }
        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "submittingdate", ResourceType = typeof(referalpersonResource))]
        public Nullable<System.DateTime> submittingdate { get; set; }
        [Display(Name = "referalstate", ResourceType = typeof(referalpersonResource))]
        public string referalstate { get; set; }
        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "referaldate", ResourceType = typeof(referalpersonResource))]
        public Nullable<System.DateTime> referaldate { get; set; }
        [Display(Name = "servicestate", ResourceType = typeof(referalpersonResource))]
        public string servicestate { get; set; }
        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "servicestartdate", ResourceType = typeof(referalpersonResource))]
        public Nullable<System.DateTime> servicestartdate { get; set; }
        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "serviceenddate", ResourceType = typeof(referalpersonResource))]
        public Nullable<System.DateTime> serviceenddate { get; set; }
        [Display(Name = "referalreicver_FK", ResourceType = typeof(referalpersonResource))]
        public string referalreicver_FK { get; set; }

        [Display(Name = "senderevalution", ResourceType = typeof(referalpersonResource))]
        public string senderevalution { get; set; }
        [Display(Name = "recieverevalution", ResourceType = typeof(referalpersonResource))]
        public string recieverevalution { get; set; }
        [Display(Name = "outreachnote", ResourceType = typeof(referalpersonResource))]
        public string outreachnote { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual center center { get; set; }
    }
}
