//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_SanadDistributedSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporal
    {
        public string idperson { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string fathername { get; set; }
        public string mothername { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string birthplace { get; set; }
        public string gender { get; set; }
        public string nationality { get; set; }
        public string martial { get; set; }
        public string relationtype { get; set; }
        public string onoffflag { get; set; }
        public string education { get; set; }
        public string educationstate { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string currentaddress { get; set; }
        public Nullable<System.DateTimeOffset> tempregistrationdate { get; set; }
        public string idcenter_FK { get; set; }
        public Nullable<int> formnumber { get; set; }
        public string note { get; set; }
        public string iduser_FK { get; set; }
    
        public virtual center center { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
